name: Starter Workflow
on: 
  workflow_call:
    inputs: 
      json-prop:
        required: true
        type: string
      json-infile:
        required: true
        type: string
    outputs:  
      json_property:
        description: value retrieved from manifest file
        value: ${{ jobs.get-manifest-properties.outputs.update_catalog}}
        
jobs:
  get-manifest-properties:
    runs-on: windows-latest
    outputs:
      update_catalog: ${{ steps.read-json.outputs.prop }}
    steps:
      - uses: actions/checkout@v3
      - name: Read json
        id: read-json
        shell: pwsh
        run: |
          $json = Get-Content integration-manifest.json | ConvertFrom-Json
          echo "::set-output name=prop::$(echo $json.update_catalog)"
